.circleci/config.yml
.gitmodules
ubuntu/goss.yaml
variant-node/goss.yaml

With the new `cimg` orb's `build-test-deploy` job, we've removed almost all of the required `config.yml` syntax for these image repos.
Here's all it takes to build, test, and optionally deploy a specific variant:
```yaml
- cimg/build-test-deploy:
name: build-test-deploy-commit-edge-master
context: image-publishing
dockerfile-path: ubuntu
image-name: cimg/base
image-tag: "$CIRCLE_SHA1"
extra-build-args: --pull
goss-yaml-dir-path: ubuntu
deploy: true
publish-tag: edge
filters: *master-filters
```
I tried to switch to a quarterly `cron` schedule, but [our `cron` interpreter doesn't support that type of syntax](https://circleci.com/docs/2.0/workflows/#specifying-a-valid-schedule), so I think we should stick with monthly for now.
I still need to actually build out the `goss.yaml` files for …

[CIRCLE-19269] Add test scaffolding, refactor config to use `cimg` orb

---

.circleci/config.yml
README.md
ubuntu/goss.yaml
variant-node/Dockerfile.template
variant-node/goss.yaml

The tests are currently very simple—just running basic commands and checking exit status—but can be expanded later
I was unable to get basic Goss tests to pass with the `nvm` installation of Node—the `nvm`, `node`, and `npm` commands consistently returned `127` error codes, and I was unable to debug them despite much effort. Instead, we juste install the latest LTS version of Node.js, using logic borrowed from the [Node orb](http://circleci.com/orbs/registry/orb/circleci/node#commands-install-node). If customers want a different version, they can run that same orb command at runtime without much trouble.

[CIRCLE-19553, CIRCLE-19323] Debug Node install issues, add more complete Goss tests

---

18.04/Dockerfile
Dockerfile.template

FIxes #22 
This PR sets explicit HOME within dockerfile so that subsequent ENV PATH commands suceed.
The result is path as intended
```
$ docker run -it test/base:18.04 bash
root@ba395af237db:~/project# echo $PATH
/root/bin:/root/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

fixes #22, uses explicit HOME path

---

.circleci/config.yml

Add the content that includes Docker creds to the test job so that Stubb
can update the Docker Hub description.

Add context to test

---

.circleci/config.yml

When Stubb was added, we need Docker creds for the test job now. It's missing.

Fix missing context for monthly release.

---

18.04/Dockerfile
Dockerfile.template

This adds the two most popular terminal text editors. This enables a better experience when users use CircleCI's "rebuild with SSH" option. Right now if they do that and want to look at/edit any file, then have to first update the apt cache and then install one of these.

Add popular editors for SSH-enabled builds.

---

.circleci/config.yml
18.04/Dockerfile
20.04/Dockerfile
Dockerfile.template
README.md
build-images.sh

Now that the shared-tools has support for multiple versions at once, we use that feature here to build both Ubuntu 18.04 and 20.04.
Closes #24.
To-Do:

Add Ubuntu 20.04 'Focal' support.

---

.circleci/config.yml

Fixes the tags specified in the monthly snapshots. This has already been fixed (and confirmed) in production with the [monthly manual override tag](https://app.circleci.com/pipelines/github/CircleCI-Public/cimg-base/243/workflows/c760e700-b39a-42c4-9ebc-fb59d168c106).

Fix LTS tags for stable and monthly snapshots.

---

.circleci/config.yml
README.md

Closes #75.
As a reminder, for those using the base image directly, you can still use Ubuntu 18.04 by adding it to the tag. For example,
`cimg/base:stable-18.04`
This PR changes which Ubuntu version is used by default. Language Convenience Images will start to be based on Ubuntu 20.04 starting September 2nd. This only affects new image tags. Any existing tag will remain unchanged.

Ubuntu 20.04 now default.

---

README.md

In the dev-hub we are going to automatically sync the content from the cimg READMEs. 
As a part of the copy in the dev-hub, the semantic versions in the `Getting Started` header are going to be updated to the latest tag.  
https://circleci.com/developer/images/image/cimg/base
Currently, the sample config is updated with the latest version semver, but the description below it mentions the text here.
As we automatically sync the content, we're simply going to update the semver in the *entire header*. This change makes the content in the header make more sense.

Update README for dev-hub parsing

---

18.04/Dockerfile
20.04/Dockerfile
Dockerfile.template

Adding the Apt package `pkg-config` to the pre-installed list. This is a compiling tool that should be helpful for many users. It's also pre-installed in Travis CI's environment.
Some info on pkg-config: https://linux.die.net/man/1/pkg-config
There was [a request for this package](https://github.com/CircleCI-Public/cimg-ruby/issues/55) for the Ruby image. Upon further review, we had it in the legacy Ruby image as an indirect installation. It's also available in the legacy buildpack-deps image. As that image will be deprecated and this image is the designated replacement, it makes sense to install this here.

Add pkg-config.

---

18.04/Dockerfile
20.04/Dockerfile
Dockerfile.template

We had layers that practically never change 1. separate and 2. near the bottom. Both bad practices. The dockerize piece could be it's own layer but they (upstream) never update it. Until we maybe replace it one day, it's basically a non-changing layer.

Optimize layer order.

---

18.04/Dockerfile
20.04/Dockerfile
Dockerfile.template

The main Docker version changed in the Dockerfiles because I forgot to generate them in that previous PR. Those are for the edge tag so it doesn't negatively impact anything.

Update Docker Compose to v1.28.3

---

18.04/Dockerfile
20.04/Dockerfile
Dockerfile.template

Related #97.
For the purpose of this image, the full vim package isn't needed. If and when this is used, it's only for SSH builds and `vim-tiny` satisfies the need.

Use smaller vim package.

---

18.04/Dockerfile
20.04/Dockerfile
Dockerfile.template

I don't why to get into the habit of installing the clients for each database. The base image is big enough as is. I'm making an exception for PostgreSQL though because within the Convenience Images, it's usage is about 100 times higher than the other databases. That tells me that this will benefit at least 80% of database users, which is our guiding metric.
Closes #91.

Add PostgreSQL Client and update yq

---

18.04/Dockerfile
20.04/Dockerfile
Dockerfile.template

The libsqllite line is because I didn't regenerate the Ubuntu versions properly in one of my recent PRs. So it's okay that it shows up here. The main PR focus is the new Docker release.

Update Docker to v20.10.11

---

18.04/Dockerfile
20.04/Dockerfile
Dockerfile.template

The initial PR worked... for some reason. I think the capitalization of the OS (i.e. Linux) changed in the download links. This PR corrects that and uses the OS-wide plugin location instead of the one for the root user.
If anyone still wants to use Docker Compose v1 btw, the suggested path is to install it with the [Docker Orb](https://circleci.com/developer/orbs/orb/circleci/docker#commands-install-docker-compose).

Fix Docker Compose v2 Installation

---

18.04/Dockerfile
20.04/Dockerfile
Dockerfile.template

This is updating a package that's already installed. This will force the update to make sure it's newer, which is good for security packages. In particular, Rust users were reporting some problems but this is also helpful for the buildpack-deps transition.

Add libssl-dev

---

.circleci/config.yml

- cibuilds/docker -> cimg/base:2022.01 image digest
- Updating the setup_remote_docker version from 19 -> 20.10.11; latest version supported
- Subbed out Stubb for Sonar; an updated tool that performs the functions of Stubb

Updates to outdated versioning and tools

---

Dockerfile.template

v4.18.1 introduced some new default behavior that appears to be a breaking change. Updating to the latest version yq v4.20.1.
**This is the issue this resolves:**
```shell
```
It seems here that the current version of yq may require `-e`, but newer versions since 4.18.1 no longer require this. Manually updating the YQ version inside the docker container appears to have resolved the issue.
**With resolution:**
Here is me running a series of bats tests which are attempting to use YQ, now using the newest version.

update yq to v4.20.1

---

18.04/Dockerfile
20.04/Dockerfile
22.04/Dockerfile
Dockerfile.template

Docker now has a repository codename for Jammy so the Jammy specific pieces have been removed.

Update Docker to v20.10.14 & remove Jammy specifics

---

18.04/Dockerfile
20.04/Dockerfile
22.04/Dockerfile
Dockerfile.template

Git fixed a [CVE announced in April](https://github.blog/2022-04-12-git-security-vulnerability-announced/) thought caused an unintended side effect for some CircleCI (and other CI provider) users. This PR opts-out of the new security change since it doesn't apply in our environment anyway.
This allows the checkout step to clone to a directory such as `/mnt/ramdisk` for example.
This change will land in `edge` after this is merged and will land in `current` in the `2022.06` release in just over a week.
Fixes #170.

Opt out of git's new security feature

---

.circleci/config.yml

As mentioned in #177, this PR promotes the `edge` tag to Ubuntu 22.04.

edge is now Ubuntu 22.04

---

.circleci/config.yml

The `stable` tag was deprecated awhile back. `current` was its replacement. This finally removes it from the build.

Remove deprecated stable tag

---

18.04/Dockerfile
20.04/Dockerfile
22.04/Dockerfile
Dockerfile.template

Reverts CircleCI-Public/cimg-base#178
This was an exciting idea when we found out that Docker started including Docker Compose in the apt repository. Unfortunately, this new install method is not working out for us. Docker doesn't publish new Docker Compose releases to the repo until they do a new Docker release. This is preventing us from releasing new Docker Compose versions within our image itself. I have an [open issue](https://github.com/docker/compose/issues/9657) upstream regarding this.
Until that gets resolved at some point, we'll go back to how we use to install Docker Compose. Not as "cool", but it worked.

Revert "Use new Docker Compose installation method"

---

.circleci/config.yml

This PR cleans up the config a bit. The main change was actually done in the CircleCI UI where we are finally able to enable **monthly** scheduled pipelines.
The monthly snapshot builds are currently set to run on the 2nd of the month at 10:00 UTC.

Adjust for monthly scheduled pipeline

---

18.04/Dockerfile
20.04/Dockerfile
22.04/Dockerfile
Dockerfile.template

Fixes #198 
This Dockerize update is mainly being done in preparation for upcoming arm64 image support. The current version we were using was amd64 only. Diving a bit deeper though...
The version of Dockerize we've been using has been stuck in time. For two reasons. 1) The original project, https://github.com/jwilder/dockerize, is no longer maintained. So there hasn't been new releases. 2) We were using a release from the project stored in our S3 bucket.
We're switching to a fork that has been accepted by many on the community. Relevant is this [GitHub Issue](https://github.com/docker/docker.github.io/issues/13548) in the official Docker Docs as well as this [follow up PR](https://github.com/docker/docker.github.io/pull/13549) that actually makes the suggestion change over to this newer …

Upgrade Dockerize to v0.8.0

---

.circleci/config.yml
build-monthly-images.sh
push-monthly-images.sh

This includes the work needed to publish the monthly updates but with support for arm64 images. This work is partially manual and doesn't fit in with the fully automated system we normally use for cimg-shared. This is okay for now because:
1. it's temporary as work continues in cimg-shared for better arm support
2. This image was always slightly an oddball anyway since it's the base image.
I'm hoping this have this system more automated by the November release.

Prep new monthly release

---

18.04/Dockerfile
20.04/Dockerfile
22.04/Dockerfile
Dockerfile.template

Closes #122
This makes the Convenience Images and VM images consistent when it comes to the `circleci` user. A great example of how this is useful is from #122. Using workspaces to move files around between executors will work much more easily with this change.

Match user/group IDs to VM images for consistency

---

18.04/Dockerfile
20.04/Dockerfile
22.04/Dockerfile
Dockerfile.template

Two libmagic support packages were installed in the Focal based image, but not directly by us. So with Jammy and "no-install-recommends" they weren't getting installed. For some packages this is okay, but libmagic is very useful in Python and Ruby worlds, and I'm sure other languages. Explicitly installing now.

Explicitly add libmagic

---

18.04/Dockerfile
20.04/Dockerfile
22.04/Dockerfile
Dockerfile.template

Upgrade yq to a version with a newer Golang compiler (4.29+) to fix CVE-2022-27664.

fix: Upgrade yq to fix vuln

---

Dockerfile.template

`lsof` is useful when checking for dangling file handlers in system tests

add lsof to base image

---

.circleci/schedule.json

schedule.json uses the wrong params. in circleci and API docs, the keys use a `-` rather than `_`

fix: use correct params in schedule.json

---

Dockerfile.template

Installs a utility named `envsubst` and its dependencies. This tool is already available on all of CircleCI's VM images, but has not yet been added to docker images.
**Purpose:** This tool can take in a string and properly replace environment values within it. This functionality is critical for basic orb functionality. Orbs currently attempt to do this using `eval` but this of course has unintended consequences. Using envsubst in orbs will allow better parameter support for environment variables.
[Example](https://www.baeldung.com/linux/envsubst-command#examples-of-use):
```sh
Hello user $USER in $DESKTOP_SESSION. It's time to say $HELLO!
```
```sh
$ export HELLO="good morning"
$ envsubst < welcome.txt
Hello user joe in Lubuntu. It's time to say good morning!
```
**Tests:** I have run …

feat: install envsubst

---

20.04/Dockerfile
22.04/Dockerfile
Dockerfile.template

Update `docker-compose` version to patch security issues (from Trivy scanner):
```
usr/local/lib/docker/cli-plugins/docker-compose (gobinary)
┌──────────────────────────────────┬─────────────────────┬──────────┬───────────────────┬───────────────┬─────────────────────────────────────────────────────────────┐
│             Library              │    Vulnerability    │ Severity │ Installed Version │ Fixed Version │                            Title                            │
├──────────────────────────────────┼─────────────────────┼──────────┼───────────────────┼───────────────┼─────────────────────────────────────────────────────────────┤
│ github.com/containerd/containerd │ CVE-2023-25153      │ MEDIUM   │ v1.6.16           │ 1.6.18        │ containerd: OCI image importer memory …
```

chore: Bump docker-compose

---

20.04/Dockerfile
22.04/Dockerfile
Dockerfile.template

Should close out https://github.com/CircleCI-Public/cimg-aws/issues/7
However, because at least one orb uses python 2, `aws-ecs-orb`, this will need to be addressed as well

chore: add python=python3 aliasing

---

20.04/Dockerfile
22.04/Dockerfile
Dockerfile.template

Update `docker-compose` version to patch security issues (from Trivy scanner):
```
usr/local/lib/docker/cli-plugins/docker-compose (gobinary)
├──────────────────────────────────┼─────────────────────┼──────────┼───────────────────┼───────────────┼──────────────────────────────────────────────────────────┤
│ github.com/opencontainers/runc   │ CVE-2023-27561      │ HIGH     │ v1.1.3            │ v1.1.5        │ runc: volume mount race condition (regression of         │
│                                  │                     │          │                   │               │ CVE-2019-19921)                                          │
│                                  │                     │          │                   │               │ https://avd.aquasec.com/nvd/cve-2023-27561 …
```

chore: Bump docker-compose for security purpose

---

.circleci/config.yml

---
The publishing of the dockerhub readme shouldn't happen in the test job. 

Publish dockerhub description in publish job

---

.circleci/config.yml

Update to non-deprecated machine image

---

Dockerfile.template

Update [Dockerfile.template](https://github.com/CircleCI-Public/cimg-base/blob/main/Dockerfile.template) to use non-legacy `ENV key=value` syntax.
When building a Docker image locally with Docker Desktop `v4.47.0` (latest version), Docker shows warnings:
> - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 120)
> - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 121)
See [LegacyKeyValueFormat](https://docs.docker.com/reference/build-checks/legacy-key-value-format/)
Docker Desktop [4.33.0](https://docs.docker.com/desktop/release-notes/#4330), released in July 2024, introduced new BuildKit checking:
> BuildKit now evaluates Dockerfile rules to inform you of potential issues.
Please check …

fix: use key=value in Dockerfile.template
