.circleci/config.yml, ubuntu/Dockerfile, ubuntu/Dockerfile.template, variant-node/Dockerfile
- add automatic linting & goss testing
- fix linting errors (improve dockerfiles to better respect best practices)
- add docker, docker-compose, dockerize, circleci CLI (dynamically determined latest stable releases)
- fix NVM install
- add very basic (dummy, essentially) goss tests (to be expande)
=> [CIRCLE-19269] Lint and test

.circleci/config.yml, variant-node/Dockerfile
- typo in nvm `RUN` step
- need to strip leading `v` from nvm version tag when comparing output to `nvm -v`
=> Fix nvm install

18.04/Dockerfile, Dockerfile.template
=> Enforce non-interactivity and PPA support.

README.md, img/circle-circleci.svg, img/circle-docker.svg, img/circle-ubuntu.svg
=> Implement proper readme.

Dockerfile.template
=> Add the autoconf package.

Dockerfile.template
=> Generate and set locale and encoding info

18.04/Dockerfile, Dockerfile.template
=> Add circleci user.

18.04/Dockerfile, Dockerfile.template
=> Fix permission on working directory.

18.04/Dockerfile, Dockerfile.template
=> Configure Apt to be non-interactive.

18.04/Dockerfile, Dockerfile.template
Very common package. I'm actually surprised I forgot to include it from the beginning.
=> Add the tzdata package.

18.04/Dockerfile, Dockerfile.template
We just updated to v19.03.10 but Docker just quickly fixed a low priority CVE.
=> Update Docker to v19.03.11.

18.04/Dockerfile, 20.04/Dockerfile, Dockerfile.template
=> Use Git ppa for newer, stable, releases

18.04/Dockerfile, 20.04/Dockerfile, Dockerfile.template
=> Update Docker to v20.10.9 & add cmake

README.md
- Added a README shield
- updated versions in the README; no variants to update
=> Add readme shield + update versions

.circleci/config.yml
tar could not write/open sonar in /usr/local/bin. created new directory for permissions
=> Make new dir with sonar update

Dockerfile.template
Added Do edit note to the Dockerfile template. Do not edit messaging is in cimg/shared
=> added do edit message to Dockerfile template

manifest
- do not merge until all images are updated; cimg/shared will have the changes to tagless-image string variable
=> added namespace variable to manifest

18.04/Dockerfile, 20.04/Dockerfile, Dockerfile.template
- discussed this with Kyle
- this will help the shellcheck orb
- its a CI tool
- we use it plenty internally
=> Pre-install shellcheck

18.04/Dockerfile, 20.04/Dockerfile, Dockerfile.template
https://github.com/mikefarah/yq/issues/1109
adds the "line" operator used in orb-tools
=> feat: update YQ to 4.21.1 - minor version change

README.md
For an example in use on a CircleCI repo (see: https://discuss.circleci.com/t/try-insights-snapshot-in-your-gh-repo/43169)
=> Add insights Snapshot

18.04/Dockerfile, 20.04/Dockerfile, 22.04/Dockerfile, Dockerfile.template
=> More 22.04 Beta Dockerfile Improvements

.circleci/config.yml
It's still in beta so no current or stable. This PR can be reverted once it's GA.
=> 22.04 doesn't get current yet

.circleci/config.yml
=> Promote Jammy to current

18.04/Dockerfile, 20.04/Dockerfile, 22.04/Dockerfile, Dockerfile.template
Closes https://github.com/CircleCI-Public/cimg-node/issues/286
=> Premake .local/bin since it's in PATH

18.04/Dockerfile, 20.04/Dockerfile, 22.04/Dockerfile, Dockerfile.template
Updating to the latest v20.10 patch. After the February snapshot goes out, we will switch over to the new v23 major release.
=> Update Docker to v20.10.23

push-base-images.sh
=> Fix edge releases for 18.04 and 20.04

Dockerfile.template
=> Add retry command

Dockerfile.template
Bump docker client and compose versions
The current docker version is near EOL and we need to prepare to support newer versions in remote docker
=> Bump docker client and compose versions

.circleci/config.yml, 20.04/Dockerfile, 22.04/Dockerfile, Dockerfile.template
---
October Release
October release version updates
=> Bump versions and release October monthly

.circleci/config.yml
removes signing for cimg-base as this is now in a holding pattern
=> [IMG-192] remove cosign

20.04/Dockerfile, 22.04/Dockerfile, Dockerfile.template, build-images.sh
=> March 2024 update

.circleci/config.yml
=> Fix readme publish

.circleci/config.yml
=> add slack notification contexts
